SUPABASE_URL = "https://jgslnkypvwscftnmudqp.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impnc2xua3lwdndzY2Z0bm11ZHFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDA5MzIsImV4cCI6MjA1OTY3NjkzMn0.oKG1qAYTJaU6kENFgVC84C59bkIqslCm0ttjtn4FErw"

